### ISSUE TITLE
xml_parsing() - zbxTelegram.py:89 - ERROR: Exception occurred: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by rmalenko** [xxsokolov/Zabbix-Notification-Telegram#10]
Привет! У менея такая ошибка
`xml_parsing() - zbxTelegram.py:89 - ERROR: Exception occurred: syntax error: line 1, column 0`

actions выглядит так, дефолтный

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<body>
		<messages>
<![CDATA[
Host: {HOST.HOST} [{HOST.IP}]
Last value: {ITEM.LASTVALUE1} ({TIME})
DESC: {INVENTORY.NOTES1}
Duration: {EVENT.AGE}]]>
		</messages>
	</body>
	<settings>
		<graphs>True</graphs>
		<graphlinks>True</graphlinks>
		<triggerlinks>True</triggerlinks>
		<tag>True</tag>
		<keyboard>True</keyboard>
		<graphs_period>10800</graphs_period>
		<itemid>{ITEM.ID1}</itemid>
		<triggerid>{TRIGGER.ID}</triggerid>
		<eventid>{EVENT.ID}</eventid>
		<actionid>{ACTION.ID}</actionid>
		<title><![CDATA[{HOST.HOST} - {EVENT.NAME}]]></title>
        <triggerurl><![CDATA[{TRIGGER.URL}]]></triggerurl>
		<tags><![CDATA[{EVENT.TAGS}]]></tags>
	</settings>
</root>
```
Спасибо

**Comment by xxsokolov** [comment]
Привет, включай дебаг и скидывай лог, ток замаж токен и юзернэйм. 

`config_debug_mode = True
config_exc_info = True’

**Comment by mrTall** [comment]
I have similar issue, clear install and XML from action.example

```
[2020-01-20 08:11:40,628] - PID:1297 - main() - zbxTelegram.py:371 - INFO: Send to @ action: Test subject
[2020-01-20 08:11:40,628] - PID:1297 - main() - zbxTelegram.py:372 - DEBUG: Send to @
action: Test subject
xml: This is the test message from Zabbix
[2020-01-20 08:11:40,628] - PID:1297 - xml_parsing() - zbxTelegram.py:96 - ERROR: Exception occurred: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxTelegram.py", line 62, in xml_parsing
    data = dict(xmltodict.parse(data, process_namespaces=True)['root'])
  File "/usr/lib/zabbix/alertscripts/venv/lib/python3.6/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

```

**Comment by mrTall** [comment]
My bad, Subject and Message MUST be "test"

**Comment by xxsokolov** [comment]
Fill it like this:
Send to: @your_username
Subject: test
Message: test

**Comment by A-Kod** [comment]
Приветствую!
Прошу помощи с аналогичной ошибкой. Дебаг запустил, вот лог (имя пользователя заменил). 
![CF331B1E-E526-4C10-BA58-98F83C9E431C](https://user-images.githubusercontent.com/17290512/74216661-282cb980-4cb6-11ea-9175-b7456726e681.jpeg)

**Comment by ghost** [comment]
Привет все у меня таже проблемма 

[2024-03-04 22:44:33,735] - PID:1907438 - xml_parsing() - zbxTelegram.py:129 - ERROR: Exception occurred: No XML in zabbix actions or it's not valid (xml parsing error). XML: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxTelegram.py", line 73, in xml_parsing
    data = dict(xmltodict.parse(data, process_namespaces=True)['root'])
  File "/usr/lib/zabbix/alertscripts/venv/lib/python3.8/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
[2024-03-04 22:44:43,742] - PID:1907463 - main() - zbxTelegram.py:498 - INFO: Send to BOT action: HOST-GROUP Problem: PostgreSQL: Cache hit ratio too low (under 90 in 5m)
[2024-03-04 22:44:43,743] - PID:1907463 - main() - zbxTelegram.py:499 - DEBUG: sys.argv: ['BOT', 'HOST-GROUP Problem: PostgreSQL: Cache hit ratio too low (under 90 in 5m)', 'Problem started at 22:44:31 on 2024.03.04\r\nProblem name: PostgreSQL: Cache hit ratio too low (under 90 in 5m)\r\nHost: pg3\r\nSeverity: Warning\r\n\r\nOriginal problem ID: 503536\r\n']
[2024-03-04 22:44:43,743] - PID:1907463 - main() - zbxTelegram.py:500 - DEBUG: Send to BOT
action: HOST-GROUP Problem: PostgreSQL: Cache hit ratio too low (under 90 in 5m)
xml: Problem started at 22:44:31 on 2024.03.04
Problem name: PostgreSQL: Cache hit ratio too low (under 90 in 5m)
Host: HOST
Severity: Warning

Original problem ID: 503536
![image](https://github.com/xxsokolov/Zabbix-Notification-Telegram/assets/37437001/87210ccc-8edb-412a-ae83-b427c8d6fd79)
