### ISSUE TITLE
Ошибка при отправке тестового сообщения:

### ISSUE THREAD

**Issue by AlexsandrChee** [xxsokolov/Zabbix-Notification-Telegram#44]
[2022-04-06 12:52:28,644] - PID:1479261 - main() - zbxTelegram.py:498 - INFO: Send to [ALERT.SENDTO] action: [ALERT.SUBJECT]
[2022-04-06 12:52:28,645] - PID:1479261 - main() - zbxTelegram.py:499 - DEBUG: sys.argv: ['[ALERT.SENDTO]', '[ALERT.SUBJECT]', '[ALERT.MESSAGE]']
[2022-04-06 12:52:28,645] - PID:1479261 - main() - zbxTelegram.py:500 - DEBUG: Send to [ALERT.SENDTO]
action: [ALERT.SUBJECT]
xml: [ALERT.MESSAGE]
[2022-04-06 12:52:28,646] - PID:1479261 - xml_parsing() - zbxTelegram.py:129 - ERROR: Exception occurred: No XML in zabbix actions or it's not valid (xml parsing error). XML: syntax error: line 1, column 0
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/zbxTelegram.py", line 73, in xml_parsing
data = dict(xmltodict.parse(data, process_namespaces=True)['root'])
File "/usr/lib/zabbix/alertscripts/venv/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

**Comment by AlexsandrChee** [comment]
ubuntu 20.04 Zabbix 5.4 Python 3.8.10
Подскажите куда копать?)

**Comment by xxsokolov** [comment]
https://github.com/xxsokolov/Zabbix-Notification-Telegram
