### ISSUE TITLE
zabbix v6.0.3    Media type test failed.

### ISSUE THREAD

**Issue by NazarovRoman** [xxsokolov/Zabbix-Notification-Telegram#46]
Media type test failed.
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/zbxTelegram.py", line 64, in <module>
loggings = System(config_debug_mode if not args.debug else True).log
File "/usr/lib/zabbix/alertscripts/zbxTelegram.py", line 50, in __init__
file_handler = logging.FileHandler(filename=config_log_file, mode='a')
File "/usr/lib64/python3.6/logging/__init__.py", line 1032, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/lib/zabbix/alertscripts/zbxTelegram_files/znt.log'

**Comment by xxsokolov** [comment]
https://github.com/xxsokolov/Zabbix-Notification-Telegram
